const sidebars = {
	tutorialSidebar: [
		'intro',
		'quick-start',
		{
			type: 'category',
			label: 'Basic Features',
			items: [
				'features/features',
				'features/auto-test',
				'features/chat-with-code',
				'features/code-completion',
				'features/devops',
				'features/fix-error',
				'features/generate-documentation',
				'features/inline-chat',
				'features/refactoring',
				'features/shell-suggest',
				'features/use-ai-in-editor',
				'features/works-with-git',
				'features/works-with-review',
			],
		},
		{
			type: 'category',
			label: 'Customize Features',
			items: [
				'customize/batch-ai-action',
				'customize/custom-action',
				'customize/custom-ext-contenxt-agent',
				'customize/custom-living-documentation',
				'customize/custom-llm-server',
				'customize/custom-quick-action',
				'customize/custom-test-template',
				'customize/customize',
				'customize/prompt-override',
				'customize/team-prompts',
				'customize/variables',
			],
		},
		{
			type: 'category',
			label: 'Agent',
			items: [
				'agent/agent',
				'agent/agent-action',
				'agent/custom-ai-agent',
				'agent/custom-request-response',
				'agent/server-example',
				'agent/bridge/bridge',
				'agent/bridge/bridge-tool',
			],
		},
		{
			type: 'category',
			label: 'AutoDev Sketch/Composer',
			items: [
				'composer/composer',
				'composer/planner',
				'composer/sketch-view',
				'composer/project-rule',
				'composer/observer',
				'composer/workspace',
				'composer/composer-prompting',
				'composer/custom-ai-composer',
			],
		},
		{
			type: 'category',
			label: 'AI Agent Language',
			items: [
				'devins/devins',
				'devins/development',
				'devins/devins-language',
				'devins/orchestration',
				'devins/quick-start',
			],
		},
		{
			type: 'category',
			label: 'MCP',
			items: [
				'mcp/development',
				'mcp/mcp',
				'mcp/mcp-client',
				'mcp/mcp-debugger',
				'mcp/mcp-server',
			],
		},
		{
		  type: 'category',
		  label: 'Scenes',
		  items: [
			  'scenes/domain-driven-design',
			  'scenes/harmony-os',
			  'scenes/legacy-migration',
			  'scenes/scenes',
			  'scenes/tdd',
			  'scenes/tech-writing',
		  ],
		},
		{
		  type: 'category',
		  label: 'Workflow',
		  items: [
			  'workflow/auto-page',
			  'workflow/auto-sql',
			  'workflow/auto-test',
			  'workflow/workflow',
		  ],
		},
		{
		  type: 'category',
		  label: 'Development',
		  items: [
			  'development/agentic-testcase',
			  'development/code-review-prompting',
			  'development/compatible-strategy',
			  'development/custom-language',
			  'development/debug-new-language',
			  'development/dev-new-language',
			  'development/development',
			  'development/development-faq',
			  'development/git-commit-prompting',
			  'development/prompt-strategy',
			  'development/refactoring-prompt',
			  'development/patterns/patterns',
			  'development/patterns/executable-unit-validation',
			  'development/patterns/by-example',
			  'development/patterns/task-driven',
			  'development/patterns/unit-driven',
		  ],
		},
		'troubleshooting',
		// 'usecases',
	],
}

export default sidebars
